apps/mascotas/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    #Urls mascotas
    path('list/', list_mascotas , name="list_mascotas"),     
    path('add/',  add_mascota, name="add_mascota"),
    path('edit/<int:id>/',edit_mascota , name="edit_mascota"),
    path('searchMascota', search_mascota, name="search_mascota"),
    path('listEspecie/', list_especie , name="list_especie"),
    path('get_list_especie/', list_especie_ajax , name="list_especie_ajax"),
    path('addEspecie/',  add_especie, name="add_especie"),
    path('editEspecie/<int:id>/',  edit_especie, name="edit_especie"),
    path('searchEspecie/', search_especie, name="search_especie"),
    path('listRaza/', list_raza , name="list_raza"),
    path('get_list_raza/', get_list_raza_ajax , name="get_list_raza_ajax"),
    path('addRaza/',  add_raza, name="add_raza"),
    path('editRaza/<int:id>/',  edit_raza, name="edit_raza"),
    path('searchRaza/', search_raza, name="search_raza"),
    path('editFichaMedica/<int:id>/', edit_ficha_medica, name="edit_ficha_medica"),
    path('historial/<int:id>/', list_historial , name="list_historial"),
    path('get_prox_vacuna/', get_prox_vacuna, name="get_prox_vacuna"),
    path('get_list_historico_vacunas_aplicadas/', get_list_historico_vacunas_aplicadas, name="get_list_historico_vacunas_aplicadas"),
    path('get_list_historico_vacunas_proximas/', get_list_historico_vacunas_proximas, name="get_list_historico_vacunas_proximas"),
]

vetoho/urls.py
import statistics
from django.contrib import admin
from django.urls import path, include
from cgitb import handler
from django.conf.urls.static import static
from vetoho import settings

#urls error page
from apps.handler.views import handler_404, handler_500

from apps.usuario.views import (Login, home_user, list_usuarios, list_usuarios_ajax, add_usuario, edit_usuario, add_rol, 
get_group_list, change_password, edit_rol, delete_rol, baja_usuario, list_usuarios_baja_ajax, alta_usuario, 
list_usuarios_baja, logoutUser)
#cliente
from apps.cliente.views import (add_ciudad, edit_ciudad, list_ciudades, get_list_ciudades, add_cliente,
edit_cliente, list_client_ajax, list_clientes, inactivar_cliente)

from apps.configuracion.servicio.views import (add_servicio, edit_servicio, bajar_servicio, list_servicio, search_servicio,
list_servicio_ajax, add_servicio_from_empleado)

from apps.configuracion.empleado.views import (add_empleado, bajar_empleado, edit_empleado, get_list_empleados_ajax, 
list_empleado, search_empleado)

urlpatterns = [
    path('SuperAdminUserDev/', admin.site.urls),
    path('', home_user, name="index"),
    path('accounts/login/', Login.as_view(), name='login'),
    path('logout/', logoutUser, name="logout"),
    
    #Usuarios
    path('usuario/listUsuarios/', list_usuarios, name="list_usuarios"),
    path('usuario/list_usuarios_ajax/', list_usuarios_ajax, name="list_usuarios_ajax"),
    path('usuario/list_usuarios_baja_ajax/', list_usuarios_baja_ajax, name="list_usuarios_baja_ajax"),
    path('usuario/add/', add_usuario , name="add_usuario"),
    path('usuario/edit/<int:id>/', edit_usuario, name="edit_usuario"),
    path('usuario/darBajaUsuario/<int:id>/', baja_usuario, name="baja_usuario"),
    path('usuario/altaUsuarios/<int:id>/', alta_usuario, name="alta_usuario"),
    path('usuario/addRol/', add_rol , name="add_rol"),
    path('usuario/editRol/<int:id>/', edit_rol , name="edit_rol"),
    path('usuario/eliminarRol/<int:id>/', delete_rol , name="delete_rol"),
    path('usuario/get_group_list/', get_group_list , name="get_group_list"),
    path('usuario/editPassword/<int:id>/', change_password , name="change_password"),
    path('usuario/listUsuariosBaja/', list_usuarios_baja, name="list_usuarios_baja"),

    #cliente urls
    path('configuracion/listCiudades/', list_ciudades , name="list_ciudades"),
    path('configuracion/get_list_ciudades/', get_list_ciudades , name="get_list_ciudades"),
    path('configuracion/addCiudad/',  add_ciudad, name="add_ciudad"),
    path('configuracion/editCiudad/<int:id>/',edit_ciudad , name="edit_ciudad"),
    path('cliente/addCliente/',add_cliente , name="add_cliente"),
    path('cliente/listCliente/', list_clientes, name="list_cliente"),
    path('cliente/get_list_client/', list_client_ajax, name="list_client_ajax"),
    path('cliente/editCliente/<int:id>/', edit_cliente, name="edit_cliente"),
    path('cliente/bajaCliente/<int:id>/', inactivar_cliente, name="inactivar_cliente"),

    #Productos
    path('producto/', include(('apps.inventario.productos.urls','producto'), namespace='producto')),
    path('deposito/', include(('apps.inventario.depositos.urls','deposito'), namespace='deposito')),

    #Servicios
    path('configuracion/listServicio/', list_servicio , name="list_servicio"),
    path('configuracion/addServicio/',  add_servicio, name="add_servicio"),
    path('configuracion/editServicio/<int:id>/',edit_servicio , name="edit_servicio"),
    path('configuracion/searchServicio/', search_servicio, name="search_servicio"),
    path('configuracion/get_list_servicio_ajax/', list_servicio_ajax , name="list_servicio_ajax"),
    path('configuracion/bajaServicio/<int:id>/', bajar_servicio, name="delete_servicio"),
    path('configuracion/addServicioFromEmpleado/', add_servicio_from_empleado, name="add_servicio_from_empleado"),


    #Empleados
    path('configuracion/listEmpleado/', list_empleado , name="list_empleado"),
    path('configuracion/get_list_servicio_ajax/', list_servicio_ajax , name="list_servicio_ajax"),
    path('configuracion/addEmpleado/',  add_empleado, name="add_empleado"),
    path('configuracion/editEmpleado/<int:id>/',edit_empleado , name="edit_empleado"),
    path('configuracion/searchEmpleado/', search_empleado, name="search_empleado"),
    path('configuracion/bajaEmpleado/<int:id>/', bajar_empleado, name="bajar_empleado"),
    path('configuracion/get_list_empleados_ajax/', get_list_empleados_ajax, name="get_list_empleados_ajax"),

    #Mascotas
    path('mascota/', include(('apps.mascotas.urls','mascota'), namespace='mascota')),   
    
    #Ventas
    path('ventas/', include(('apps.ventas.urls','ventas'), namespace='venta')),

    #Configuraciones
    path('configuracion/', include(('apps.configuracion.configuracion_inicial.urls','configuracion_inicial'), namespace='configuracion_inicial')),

    #Utiles
    path('utiles/', include(('apps.utiles.urls','configuracion_inicial'), namespace='utiles')),
    
    #Vacunas
    path('configuracion/', include(('apps.configuracion.tipo_vacuna.urls','tipo_vacuna'), namespace='tipo_vacuna')),
    
    #Vacunas
    path('reserva/', include(('apps.agendamientos.urls','reserva'), namespace='reserva')),
    
    #Compras
    path('compra/', include(('apps.compras.urls','compra'), namespace='compra')),

    #Reporte
    path('reporte/', include(('apps.reportes.urls','reporte'), namespace='reporte')),
    #Caja
    path('caja/', include(('apps.caja.urls','caja'), namespace='caja')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404=handler_404
handler500=handler_500

apps/mascotas/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib import messages
from django.db.models import Q
from django.core.paginator import Paginator
from django.http import JsonResponse
from datetime import date, datetime
import json
import math

from apps.configuracion.tipo_vacuna.models import TipoVacuna
from apps.inventario.productos.models import Producto

from .models import (Especie, Mascota, Raza, 
                     FichaMedica, Vacuna, Consulta, Antiparasitario, HistoricoFichaMedica)
from .forms import (EspecieForm, MascotaForm, RazaForm,
FichaMedicaForm, VacunaForm, ConsultaForm, AntiparasitarioForm)

# Create your views here.

@login_required()
@permission_required('mascota.add_especie')
def add_especie(request):
    form = EspecieForm
    if request.method == 'POST':
        form = EspecieForm(request.POST or None)
        if form.is_valid():
            messages.success(request, 'Se ha agregado correctamente!')
            form.save()
            return redirect('/mascota/listEspecie/')
    context = {'form' : form}
    return render(request, 'mascota/especie/add_especie_modal.html', context)


@login_required()
@permission_required('mascota.change_especie')
def edit_especie(request, id):
    especie = Especie.objects.get(id=id)
    form = EspecieForm(instance=especie)
    if request.method == 'POST':
        form = EspecieForm(request.POST, instance=especie)
        if not form.has_changed():
            messages.info(request, "No has hecho ningun cambio!")
            return redirect('/mascota/listEspecie/')
        if form.is_valid():
            especie = form.save(commit=False)
            especie.save()
            messages.success(request, 'Se ha editado correctamente!')
            return redirect('/mascota/listEspecie/')
    context = {'form' : form, 'especie': especie}
    return render(request, 'mascota/especie/add_especie_modal.html', context)

@login_required()
@permission_required('mascota.view_especie')
def list_especie(request):
    especie = Especie.objects.all().order_by('-last_modified')
    paginator = Paginator(especie, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj' : page_obj}
    return render(request, "mascota/especie/list_especie.html", context)

#@login_required()
def list_especie_ajax(request):
    query = request.GET.get('busqueda')
    if query != "":
        especie = Especie.objects.filter(Q(nombre_especie__icontains=query))
    else:
        especie = Especie.objects.all().order_by('-last_modified')

    total = especie.count()


    _start = request.GET.get('start')
    _length = request.GET.get('length')
    if _start and _length:
        start = int(_start)
        length = int(_length)

        especie = especie[start:start + length]

    data = [{'id': espe.id, 'nombre': espe.nombre_especie} for espe in especie]        

    response = {
        'data': data,
        'recordsTotal': total,
        'recordsFiltered': total,
    }
    return JsonResponse(response)    

#@login_required()
def search_especie(request):
    query = request.GET.get('q')
    if query:
        especie = Especie.objects.filter(Q(nombre_especie__icontains=query))
    else:
        especie = Especie.objects.all().order_by('-last_modified')
    paginator = Paginator(especie, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = { 'page_obj': page_obj}
    return render(request, "mascota/especie/list_especie.html", context)

"""
Functions of Razas
"""
@login_required()
@permission_required('mascota.add_raza')
def add_raza(request):
    form = RazaForm
    if request.method == 'POST':
        form = RazaForm(request.POST or None)
        if form.is_valid():
            form.save()
            messages.success(request, 'Se ha agregado correctamente!')
            return redirect('/mascota/listRaza/')
    context = {'form' : form}
    return render(request, 'mascota/raza/add_raza_modal.html', context)

@login_required()
@permission_required('mascota.change_raza')
def edit_raza(request, id):
    raza = Raza.objects.get(id=id)
    form = RazaForm(instance=raza)
    if request.method == 'POST':
        form = RazaForm(request.POST, instance=raza)
        if not form.has_changed():
            messages.info(request, "No has hecho ningun cambio!")
            return redirect('/mascota/listRaza/')
        if form.is_valid():
            raza = form.save(commit=False)
            raza.save()
            messages.success(request, 'Se ha editado correctamente!')
            return redirect('/mascota/listRaza/')
    context = {'form' : form, 'raza': raza}
    return render(request, 'mascota/raza/add_raza_modal.html', context)    

@login_required()
@permission_required('mascota.view_raza')
def list_raza(request):
    raza = Raza.objects.all().order_by('-last_modified')
    raza_especie = RazaForm
    paginator = Paginator(raza, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj' : page_obj, 'form': raza_especie}
    return render(request, "mascota/raza/list_raza.html", context)

#@login_required()
def get_list_raza_ajax(request):
    query = request.GET.get('busqueda')
    if query != "":
        raza = Raza.objects.filter(Q(nombre_raza__icontains=query) | Q(id_especie__nombre_especie__icontains=query) )
    else:
        raza = Raza.objects.all().order_by('-last_modified')

    total = raza.count()

    _start = request.GET.get('start')
    _length = request.GET.get('length')
    if _start and _length:
        start = int(_start)
        length = int(_length)

        raza = raza[start:start + length]

    data = [{'id': ra.id, 'nombre_raza': ra.nombre_raza, 'nombre_especie': ra.id_especie.nombre_especie } for ra in raza]        

    response = {
        'data': data,
        'recordsTotal': total,
        'recordsFiltered': total,
    }
    return JsonResponse(response) 

#@login_required()
def search_raza(request):
    query = request.GET.get('q')
    if query:
        raza = Raza.objects.filter(Q(nombre_raza__icontains=query))
    else:
        raza = Raza.objects.all().order_by('-last_modified')
    paginator = Paginator(raza, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = { 'page_obj': page_obj}
    return render(request, "mascota/raza/list_raza.html", context)


@login_required()
@permission_required('mascota.view_mascota')
def list_mascotas(request):
    mascotas = Mascota.objects.all().order_by('-last_modified')
    paginator = Paginator(mascotas, 8)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj' : page_obj}
    return render(request, "mascota/mascota/list_mascota.html", context)


date = datetime.now()
# Create your views here.
@login_required()
@permission_required('mascota.add_mascota')
def add_mascota(request):
    form = MascotaForm    
    if request.method == 'POST':
        form = MascotaForm(request.POST, request.FILES)
        if form.is_valid():           
            form.save()
            messages.success(request, 'Se ha agregado correctamente!')
            return redirect('/mascota/list')
    context = {'form' : form}
    return render(request, 'mascota/mascota/add_mascota.html', context)


@login_required()
@permission_required('mascota.view_mascota')
def edit_mascota(request, id):
    mascota = Mascota.objects.get(id=id)
    form = MascotaForm(instance=mascota)
    if request.method == 'POST':
        form = MascotaForm(request.POST, request.FILES, instance=mascota)
        if not form.has_changed():
            messages.info(request, "No has hecho ningun cambio!")
            return redirect('/mascota/edit/' + str(id))
        if form.is_valid():
            mascota = form.save(commit=False)
            mascota.save()
            messages.success(request, 'Se ha editado correctamente!')
            return redirect('/mascota/edit/' + str(id))

    context = {'form': form, 'mascota': mascota}
    return render(request, 'mascota/mascota/edit_mascota.html', context)

@login_required()
def search_mascota(request):
    query = request.GET.get('q')
    if query:
        mascota = Mascota.objects.filter(
            Q(nombre_mascota__icontains=query) | 
            Q(id_cliente__nombre_cliente__icontains=query) | 
            Q(id_cliente__apellido_cliente__icontains=query))
    else:
        mascota = Mascota.objects.all().order_by('-last_modified')
    paginator = Paginator(mascota, 8)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = { 'page_obj': page_obj}
    return render(request, "mascota/mascota/list_mascota.html", context)


#Funciones de Ficha Medicas
@login_required()
@permission_required('mascota.view_mascota')
def edit_ficha_medica(request,id):
    mascota = Mascota.objects.get(id=id)
    fichaMedicaGet = FichaMedica.objects.get(id_mascota=id)
    vacunaGet = Vacuna.objects.get(id_ficha_medica=fichaMedicaGet.id)
    consultaGet = Consulta.objects.get(id_ficha_medica=fichaMedicaGet.id)
    antiparasitarioGet = Antiparasitario.objects.get(id_ficha_medica=fichaMedicaGet.id)
    historicoFichaMedica = HistoricoFichaMedica
    vacuna_aplicado = []
    vacuna_proxima = []
    vacunas = TipoVacuna.objects.all()
    try:    
        if request.method == 'POST':
            formFichaMedica = FichaMedicaForm(request.POST, instance=fichaMedicaGet)
            formVacuna = VacunaForm(request.POST, instance=vacunaGet)
            formConsulta = ConsultaForm(request.POST, instance=consultaGet)
            formAntiparasitario = AntiparasitarioForm(request.POST, instance=antiparasitarioGet)
            if not formVacuna.has_changed() and not formConsulta.has_changed() and not formAntiparasitario.has_changed():

templates/mascota/raza/add_raza_modal.html
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel"><b>Razas
            </b></h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% if raza %}
            <form action="{% url 'mascota:edit_raza' raza.id %}" method="POST" role="form" id="form">
        {% else %}
            <form action="{% url 'mascota:add_raza' %}" method="POST" role="form" id="form">
        {% endif %}
            {% csrf_token %}
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-10">
                        <div class="form-group">
                            <label>{{form.nombre_raza.label}}<span class="required"> *</span></label>
                                {{form.nombre_raza}}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-10">
                        <div class="form-group">
                            <label>Especie <span class="required"> *</span></label>
                                {{form.id_especie}}
                    </div>
                </div>
                <div style="color:red;">(*) Campos a completar</div>
            </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                <button type="submit" class="btn btn-primary">{%if raza%}Editar {%else%}Agregar {%endif%}</button>
            </div>
        </form>
    </div>
</div>

templates/mascota/raza/list_raza.html
{% extends "base/base.html" %}
{% load static %}

{% block title %} Lista Dépositos {% endblock title %}

{% block css %}
{{ block.super }}

<style>
  .icon-info {
    left: 169px !important;
    bottom: 4px !important;
      z-index: 1;
  }
</style>
{% endblock css %}

{% block content %}
 <!-- Content Header (Page header) -->
 <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>Lista de Razas
          </h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{% url 'index' %}">Inicio</a></li>
            <li class="breadcrumb-item active">Razas</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
   <!-- Main content -->
   <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-12">
          <div class="card">            
            <div class="card-header">
                <button class="btn btn-primary float-right"
                    onclick="abrir_modal_creacion('/mascota/addRaza/');">
                    Agregar Raza
                </button>

                <div class="float-left">
                    <div class="wrap">
                        <div class="input-group">
                            <input type="search" class="form-control searchTerm" id="searchTerm"
                                placeholder="Buscar"
                                data-toggle="tooltip" data-placement="top"
                                title="Buscar por nombre raza">
                                {% include 'base/partials/info_search.html' %}
                            <div class="input-group-append">
                                <button type="button" class="btn btn-default searchButton" type="button" id="busqueda">
                                    <i class="fa fa-search"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                </div> 
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <table id="list_raza" class="table table-striped table-hover">
                <thead>
                <tr>
                  <th>Nombre de la Raza</th>
                  <th>Nombre de la Especie</th>
                  <th>Acciones</th>
                </tr>
                </thead>
                <tbody>                   
                </tbody>   
              </table>
            </div>
            <!-- /.card-body -->
          </div>                    
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
    </section>

    <div class="modal fade" id="creacion" role="dialog"></div>

    <div class="modal fade" id="edicion" role="dialog">
    </div>

{% endblock content %}

{% block js_page %}
{{ block.super }}
<!-- Datatables -->
<script>
    $(function () {
        $('input').on("cut copy paste",function(e) {
            e.preventDefault();
        });

        var get_list = function (busqueda) {
            $("#list_raza").DataTable({
                destroy: true,  
                searching: false,
                pageLength: 10,
                ajax: {
                    url: "/mascota/get_list_raza/",
                    type: 'GET',
                    datatype: 'json',
                    data: {'busqueda': busqueda},
                    error: function (data) {
                        $.fn.DataTable.ext.errorMode = 'none'
                    }
                },
                columns: [
                    {data: 'nombre_raza'},                   
                    {data: 'nombre_especie'},                   
                    {
                        name: 'Acciones',
                        data: 'id',
                        render: function (data, type, row) {

                            var buttons = "";

                            buttons +=  '<button class="btn btn-warning btn-circle btn-sm" onclick="abrir_modal_edicion(\'/mascota/editRaza/' +row.id+ '/\')">\
                                            <a style="color: black"> Editar </a>\
                                        </button>';
                            
                            //buttons += ' <button class="btn btn-danger btn-circle btn-sm" onclick="eliminar_registro(\'/deposito/baja/' +row.id+ '/\',\'/deposito/list\')">Dar de Baja</button>';

                            return buttons;
                        },
                        orderable: false
                    }

                ],
                serverSide: false,
                language: {                    
                    decimal: "",
                    emptyTable: "Sin resultados encontrados",
                    info: "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
                    infoEmpty: "Mostrando 0 de 0 Entradas",
                    infoFiltered: "(Filtrado de _MAX_ total entradas)",
                    infoPostFix: "",
                    thousands: ",",
                    lengthMenu: "Mostrar _MENU_ Entradas",
                    loadingRecords: "Cargando...",
                    processing: "Procesando...",
                    search: "Buscar:",
                    zeroRecords: "Sin resultados encontrados",
                    paginate: {
                        first: "Primero",
                        last: "Ultimo",
                        next: "Siguiente",
                        previous: "Anterior",
                    },
                },

            })

        }

        var query = ""
        
        get_list(query);

        $("#searchTerm").change(function(){
            var busqueda = $("#searchTerm").val()
            sessionStorage.setItem("busqueda", busqueda)
        })

        $("#busqueda").click(function(){
            var busqueda = sessionStorage.getItem("busqueda")
            if(busqueda == "" || busqueda == undefined || busqueda == null){
                busqueda = "";
                get_list(busqueda)
            }
            else{
                get_list(busqueda)
            }
        })

        {% if messages %}
          {% for message in messages %}
              var text = "{{ message }}";
              add_edit_registro(text);
          {% endfor %}
        {% endif %}
    })
</script>
{% endblock js_page %}