apps/inventario/depositos/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    #Urls deposito
    path('add/',add_deposito , name="add_deposito"),
    path('list/', list_deposito, name="list_deposito"),
    path('get_list_deposito/', get_list_deposito, name="get_list_deposito"),
    path('edit/<int:id>/', edit_deposito, name="edit_deposito"),
]

apps/inventario/productos/urls.py
from django.urls import path
from apps.inventario.productos.views import (add_producto,edit_producto,list_producto_general_ajax,
list_productos_general,list_tipo_producto,get_list_tipo_producto,add_tipo_producto,alta_tipo_producto,
edit_tipo_producto,baja_tipo_producto,vence_si_no, add_tipo_producto_from_producto, get_producto_antiparasitario,
list_producto, list_producto_vencido_ajax, mover_producto, search_producto, delete_producto, mover_producto_detalle_general,
list_ajuste_inventario_ajax,list_ajustar_inventario, add_ajuste_inventario, list_ajuste_inventario_historial_ajax,
list_ajustar_historial_inventario,get_producto_inventario, list_historico_producto,get_historico_producto)

urlpatterns = [
    #Urls tipo producto
    path('tipoProducto/add/',add_tipo_producto , name="add_tipo_producto"),
    path('tipoProducto/list/', list_tipo_producto, name="list_tipo_producto"),
    path('tipoProducto/edit/<int:id>/', edit_tipo_producto, name="edit_tipo_producto"),
    path('tipoProducto/baja/<int:id>/', baja_tipo_producto, name="baja_tipo_producto"),
    path('tipoProducto/alta/<int:id>/', alta_tipo_producto, name="alta_tipo_producto"),
    path('tipoProducto/vence_si_no/', vence_si_no, name="vence_si_no"),
    path('tipoProducto/get_list_tipo_producto/', get_list_tipo_producto, name="get_list_tipo_producto"),

    path('add/', add_producto, name="add_producto"),
    path('listDetalle/<int:id>/', list_producto, name="list_producto"),
    path('listGeneral/', list_productos_general, name="list_productos_general"),
    path('list_general_ajax/', list_producto_general_ajax, name="list_producto_general_ajax"),
    path('list_producto_vencido_ajax/', list_producto_vencido_ajax, name="list_producto_vencido_ajax"),
    path('edit/<int:id>/', edit_producto, name="edit_producto"),
    path('mover/<int:id>/', mover_producto, name="mover_producto"),
    path('search/', search_producto, name="search_producto"),
    path('darBaja/<int:id>', delete_producto, name="delete_producto"),
    path('moverGeneral/<int:id>/', mover_producto_detalle_general, name="mover_producto_detalle_general"),
    path('list_ajuste_inventario_ajax/', list_ajuste_inventario_ajax, name="list_ajuste_inventario_ajax"),
    path('list_ajustar_inventario/', list_ajustar_inventario, name="list_ajustar_inventario"),
    path('addAjusteInventario/', add_ajuste_inventario, name="add_ajuste_inventario"),
    path('list_ajuste_inventario_historial_ajax/', list_ajuste_inventario_historial_ajax, name="list_ajuste_inventario_historial_ajax"),
    path('list_ajustar_historial_inventario/', list_ajustar_historial_inventario, name="list_ajustar_historial_inventario"),
    path('get_producto_inventario/', get_producto_inventario, name="get_producto_inventario"),
    path('get_producto_antiparasitario/', get_producto_antiparasitario, name="get_producto_antiparasitario"),
    path('listHistoricoCompra/<int:id>/', list_historico_producto, name="list_historico_producto"),
    path('get_historico_producto/<int:id>/', get_historico_producto, name="get_historico_producto"),
   
]

vetoho/urls.py
import statistics
from django.contrib import admin
from django.urls import path, include
from cgitb import handler
from django.conf.urls.static import static
from vetoho import settings

#urls error page
from apps.handler.views import handler_404, handler_500

from apps.usuario.views import (Login, home_user, list_usuarios, list_usuarios_ajax, add_usuario, edit_usuario, add_rol, 
get_group_list, change_password, edit_rol, delete_rol, baja_usuario, list_usuarios_baja_ajax, alta_usuario, 
list_usuarios_baja, logoutUser)
#cliente
from apps.cliente.views import (add_ciudad, edit_ciudad, list_ciudades, get_list_ciudades, add_cliente,
edit_cliente, list_client_ajax, list_clientes, inactivar_cliente)

from apps.configuracion.servicio.views import (add_servicio, edit_servicio, bajar_servicio, list_servicio, search_servicio,
list_servicio_ajax, add_servicio_from_empleado)

from apps.configuracion.empleado.views import (add_empleado, bajar_empleado, edit_empleado, get_list_empleados_ajax, 
list_empleado, search_empleado)

urlpatterns = [
    path('SuperAdminUserDev/', admin.site.urls),
    path('', home_user, name="index"),
    path('accounts/login/', Login.as_view(), name='login'),
    path('logout/', logoutUser, name="logout"),
    
    #Usuarios
    path('usuario/listUsuarios/', list_usuarios, name="list_usuarios"),
    path('usuario/list_usuarios_ajax/', list_usuarios_ajax, name="list_usuarios_ajax"),
    path('usuario/list_usuarios_baja_ajax/', list_usuarios_baja_ajax, name="list_usuarios_baja_ajax"),
    path('usuario/add/', add_usuario , name="add_usuario"),
    path('usuario/edit/<int:id>/', edit_usuario, name="edit_usuario"),
    path('usuario/darBajaUsuario/<int:id>/', baja_usuario, name="baja_usuario"),
    path('usuario/altaUsuarios/<int:id>/', alta_usuario, name="alta_usuario"),
    path('usuario/addRol/', add_rol , name="add_rol"),
    path('usuario/editRol/<int:id>/', edit_rol , name="edit_rol"),
    path('usuario/eliminarRol/<int:id>/', delete_rol , name="delete_rol"),
    path('usuario/get_group_list/', get_group_list , name="get_group_list"),
    path('usuario/editPassword/<int:id>/', change_password , name="change_password"),
    path('usuario/listUsuariosBaja/', list_usuarios_baja, name="list_usuarios_baja"),

    #cliente urls
    path('configuracion/listCiudades/', list_ciudades , name="list_ciudades"),
    path('configuracion/get_list_ciudades/', get_list_ciudades , name="get_list_ciudades"),
    path('configuracion/addCiudad/',  add_ciudad, name="add_ciudad"),
    path('configuracion/editCiudad/<int:id>/',edit_ciudad , name="edit_ciudad"),
    path('cliente/addCliente/',add_cliente , name="add_cliente"),
    path('cliente/listCliente/', list_clientes, name="list_cliente"),
    path('cliente/get_list_client/', list_client_ajax, name="list_client_ajax"),
    path('cliente/editCliente/<int:id>/', edit_cliente, name="edit_cliente"),
    path('cliente/bajaCliente/<int:id>/', inactivar_cliente, name="inactivar_cliente"),

    #Productos
    path('producto/', include(('apps.inventario.productos.urls','producto'), namespace='producto')),
    path('deposito/', include(('apps.inventario.depositos.urls','deposito'), namespace='deposito')),

    #Servicios
    path('configuracion/listServicio/', list_servicio , name="list_servicio"),
    path('configuracion/addServicio/',  add_servicio, name="add_servicio"),
    path('configuracion/editServicio/<int:id>/',edit_servicio , name="edit_servicio"),
    path('configuracion/searchServicio/', search_servicio, name="search_servicio"),
    path('configuracion/get_list_servicio_ajax/', list_servicio_ajax , name="list_servicio_ajax"),
    path('configuracion/bajaServicio/<int:id>/', bajar_servicio, name="delete_servicio"),
    path('configuracion/addServicioFromEmpleado/', add_servicio_from_empleado, name="add_servicio_from_empleado"),


    #Empleados
    path('configuracion/listEmpleado/', list_empleado , name="list_empleado"),
    path('configuracion/get_list_servicio_ajax/', list_servicio_ajax , name="list_servicio_ajax"),
    path('configuracion/addEmpleado/',  add_empleado, name="add_empleado"),
    path('configuracion/editEmpleado/<int:id>/',edit_empleado , name="edit_empleado"),
    path('configuracion/searchEmpleado/', search_empleado, name="search_empleado"),
    path('configuracion/bajaEmpleado/<int:id>/', bajar_empleado, name="bajar_empleado"),
    path('configuracion/get_list_empleados_ajax/', get_list_empleados_ajax, name="get_list_empleados_ajax"),

    #Mascotas
    path('mascota/', include(('apps.mascotas.urls','mascota'), namespace='mascota')),   
    
    #Ventas
    path('ventas/', include(('apps.ventas.urls','ventas'), namespace='venta')),

    #Configuraciones
    path('configuracion/', include(('apps.configuracion.configuracion_inicial.urls','configuracion_inicial'), namespace='configuracion_inicial')),

    #Utiles
    path('utiles/', include(('apps.utiles.urls','configuracion_inicial'), namespace='utiles')),
    
    #Vacunas
    path('configuracion/', include(('apps.configuracion.tipo_vacuna.urls','tipo_vacuna'), namespace='tipo_vacuna')),
    
    #Vacunas
    path('reserva/', include(('apps.agendamientos.urls','reserva'), namespace='reserva')),
    
    #Compras
    path('compra/', include(('apps.compras.urls','compra'), namespace='compra')),

    #Reporte
    path('reporte/', include(('apps.reportes.urls','reporte'), namespace='reporte')),
    #Caja
    path('caja/', include(('apps.caja.urls','caja'), namespace='caja')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404=handler_404
handler500=handler_500

apps/inventario/depositos/forms.py
from django import forms

from apps.inventario.depositos.models import Deposito

class DepositoForm(forms.ModelForm):
    """[summary]

    Args:
        forms ([DepositoForm]): [Formulario de deposito]
    """    
    class Meta:
        model = Deposito
        fields = '__all__'
        labels = {
            'descripcion' : 'Descripción ',
        }
        widgets = {
			'descripcion' : forms.TextInput(attrs={'class':'form-control','autocomplete': 'off', 
            'name': 'descripcion', 'placeholder': 'Descripcion', 'required': 'required', 
            'onkeyup':'aceptarLetras(this)','onchange': 'validateSpaceBlank(this)'}),
		}

apps/inventario/productos/forms.py
from django import forms

from apps.inventario.productos.models import TipoProducto
from apps.inventario.productos.models import Producto

class TipoProductoForm(forms.ModelForm):
    """[summary]
    Args:
        forms ([TipoProductoForm]): [Formulario de tipo de producto]
    """    
    class Meta:
        model = TipoProducto
        exclude = ['is_active']
        labels = {
            'nombre_tipo' : 'Nombre',
            'vence' : 'Vence'
        }
        widgets = {
            'nombre_tipo' : forms.TextInput(attrs={'class':'form-control', 'autocomplete': 'off','name': 'nombre_tipo', 
                                                   'placeholder': 'Nombre Tipo Producto', 'required': 'required', 'onkeyup':'aceptarLetras(this)'
                                                   ,'onchange': 'validateSpaceBlank(this)'}),
            'vence' : forms.Select(attrs={'class':'form-control', 'id': 'vence','required':'required' ,'name':'vence'}),
			'fecha_alta' : forms.TextInput(attrs={'class':'form-control','type':'datetime',
            'name': 'fecha_alta', 'placeholder': 'Fecha de Alta', 'readonly': 'readonly'}),
		    'fecha_baja' : forms.TextInput(attrs={'class':'form-control','type':'datetime', 'name': 'fecha_baja', 
            'placeholder': 'Fecha de Baja', 'readonly': 'readonly'}),
		}

class ProductoForm(forms.ModelForm):
    """[summary]

    Args:
        forms ([ProductoForm]): [Formulario de producto]
    """    
    class Meta:
        model = Producto
        exclude = ['is_active']
        widgets = {
			 'codigo_producto' : forms.TextInput(attrs={'class':'form-control', 'name': 'codigo_producto',
                'autocomplete': 'off' ,'placeholder': 'Codigo Producto', 'onkeyup':'aceptarNumerosYLetras(this)'}),
            'nombre_producto': forms.TextInput(attrs={'class':'form-control', 'name': 'nombre_producto', 
                'autocomplete': 'off' ,'placeholder': 'Nombre del producto', 'required': 'required', 
                'onkeyup':'aceptarNumerosYLetras(this)','onchange': 'validateSpaceBlank(this)'}),
            'descripcion' : forms.TextInput(attrs={'class':'form-control', 'name': 'descripcion', 
                'autocomplete': 'off' ,'placeholder': 'Descripcion', 'required': 'required', 
                'onkeyup':'aceptarNumerosYLetras(this)','onchange': 'validateSpaceBlank(this)'}),
            'fecha_vencimiento' : forms.TextInput(attrs={'class':'form-control fecha_vencimiento','type':'text', 
                'autocomplete': 'off' ,'id':'datepicker' ,'name': 'fecha_vencimiento', 'placeholder': 'Fecha de Vencimiento'}),
            'fecha_baja' : forms.TextInput(attrs={'class':'form-control','type':'text', 
                        'autocomplete': 'off' ,'name': 'fecha_baja', 'placeholder': 'Fecha de Baja'}),
            'fecha_movimiento' : forms.TextInput(attrs={'class':'form-control','type':'text', 'autocomplete': 'off' ,
                'name': 'fecha_movimiento', 'placeholder': 'Fecha de Movimiento'}),
            'iva' : forms.Select(attrs={'class':'form-control', 'id': 'iva','required':'required' ,'name':'iva'}),
            'fecha_compra' : forms.TextInput(attrs={'class':'form-control','type':'text', 'name': 'fecha_compra', 
                    'autocomplete': 'off' ,
                'placeholder': 'Fecha de Compra', 'readonly': 'readonly'}),
			'precio_compra': forms.TextInput(attrs={'class':'form-control','name': 'precio_compra', 
                    'autocomplete': 'off' ,'placeholder': 'Precio de compra', 'onkeyup':'aceptarNumeros(this)',
                    'value':'0', 'disabled': 'disabled'}),
            'precio_venta': forms.TextInput(attrs={'class':'form-control', 'required':'required',
                'name': 'precio_venta','autocomplete': 'off' , 'placeholder': 'Precio de Venta', 'onkeyup':'aceptarNumeros(this)'}),
            'stock_minimo': forms.TextInput(attrs={'class':'form-control', 'required':'required',
                'name': 'stock_minimo','autocomplete': 'off' , 'placeholder': 'Stock Minimo', 'onkeyup':'aceptarNumeros(this)'}),
            'stock_fisico': forms.TextInput(attrs={'class':'form-control','name': 'stock_fisico',
                'autocomplete': 'off' , 'placeholder': 'Stock Fisico', 'onkeyup':'aceptarNumeros(this)'}),
            'lote': forms.TextInput(attrs={'class':'form-control', 'name': 'lote', 'placeholder': 'Lote', 
                'autocomplete': 'off' ,'id':'lote_id','onkeyup':'aceptarNumerosYLetras(this)'}),
            'stock': forms.TextInput(attrs={'id':'stock', 'required':'required','class':'form-control', 
                'name': 'stock', 'autocomplete': 'off' ,'placeholder': 'Stock', 'onkeyup':'aceptarNumeros(this)'}),
            'tipo_producto' : forms.Select(attrs={'class':'form-control', 'id': 'tipo_producto', 
                'autocomplete': 'off' ,'required':'required' ,'name':'tipo_producto'}),
            'id_deposito' : forms.Select(attrs={'class':'form-control', 'id': 'id_deposito',
                'autocomplete': 'off' ,'required':'required' ,'name':'id_deposito'})
		}        

apps/inventario/depositos/views.py
import math
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib import messages
from django.db.models import Q
from django.core.paginator import Paginator
from django.views.decorators.csrf import csrf_exempt

from datetime import datetime
import json
from django.http import JsonResponse

from apps.inventario.depositos.forms import DepositoForm
from apps.inventario.depositos.models import Deposito

date = datetime.now()

# Create your views here.

#Metodo para agregar deposito
@login_required()
@permission_required('depositos.view_deposito')
def add_deposito(request):
    form = DepositoForm
    if request.method == 'POST':
        form = DepositoForm(request.POST or None)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Deposito agregado correctamente!')
            return redirect('/deposito/list')   
    context = {'form' : form}
    return render(request, 'inventario/depositos/add_deposito.html', context)

# Metodo para editar deposito
@login_required()
@permission_required('depositos.change_deposito')
def edit_deposito(request, id):
    deposito = Deposito.objects.get(id=id)
    form = DepositoForm(instance=deposito)
    if request.method == 'POST':
        form = DepositoForm(request.POST, instance=deposito)
        if not form.has_changed():
            messages.info(request, "No ha hecho ningun cambio")
            return redirect('/deposito/list/')
        if form.is_valid():
            deposito = form.save(commit=False)
            deposito.save()
            messages.add_message(request, messages.SUCCESS, 'El depósito se ha editado correctamente!')
            return redirect('/deposito/list/')

    context = {'form': form, 'deposito': deposito}
    return render(request, 'inventario/depositos/add_deposito.html', context)

#Metodo para listar todos los depositos
@login_required()
@permission_required('depositos.view_deposito')
def list_deposito(request):
    return render(request, "inventario/depositos/list_deposito.html")


def get_list_deposito(request):
    query = request.GET.get('busqueda')
    if query:
        depositos = Deposito.objects.filter(Q(descripcion__icontains=query)).order_by('-last_modified')
    else:
        depositos = Deposito.objects.all().order_by('-last_modified')

    total = depositos.count()

    _start = request.GET.get('start')
    _length = request.GET.get('length')
    if _start and _length:
        start = int(_start)
        length = int(_length)
        page = math.ceil(start / length) + 1
        per_page = length

        depositos = depositos[start:start + length]

    data = [{'id': de.id, 'descripcion': de.descripcion } for de in depositos]        

    response = {
        'data': data,
        'recordsTotal': total,
        'recordsFiltered': total,
    }
    return JsonResponse(response) 

templates/inventario/tipoProducto/add_tipo_producto.html
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel"><b>Tipo de Producto
                </b></h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% if from_add != 'S' %}
        <form action="{% url 'producto:add_tipo_producto' %}" method="POST" role="form" id="form">
        {% else %}
        <form action="{% url 'producto:add_tipo_producto_from_producto' %}" method="POST" role="form" id="form">
            {% endif %}
            {% csrf_token %}
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>{{form.nombre_tipo.label}}<span class="required"> *</span></label>
                            {{form.nombre_tipo}}
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>{{form.vence.label}}<span class="required"> *</span></label>
                            {{form.vence}}
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                <button type="submit" class="btn btn-primary">Agregar</button>
            </div>
        </form>
    </div>
</div>

templates/inventario/tipoProducto/edit_tipo_producto.html
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel"><b>Tipo de Producto
            </b></h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
            <form action="{% url 'producto:edit_tipo_producto' tipo_producto.id %}" method="POST" role="form" id="form">
            {% csrf_token %}
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>{{form.nombre_tipo.label}}<span class="required"> *</span></label>
                                {{form.nombre_tipo}}
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>{{form.vence.label}}<span class="required"> *</span></label>
                                {{form.vence}}
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                <button type="submit" class="btn btn-primary">Editar</button>
            </div>
        </form>
    </div>
</div>

templates/inventario/tipoProducto/list_tipo_producto.html
{% extends "base/base.html" %}
{% load static %}

{% block title %} Lista Tipo Producto {% endblock title %}

{% block css %}
{{ block.super }}

<style>

</style>
{% endblock css %}

{% block content %}
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Tipo de Productos
                </h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{% url 'index' %}">Inicio</a></li>
                    <li class="breadcrumb-item active">Tipo de Productos</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <div class="float-left">
                            <form>
                                <div class="input-group">
                                    <input type="search" class="form-control form-control-lg" id="searchTerm"
                                        data-toggle="tooltip" data-placement="top" title="Buscar por nombre tipo"
                                        placeholder="Buscar por nombre tipo">
                                        {% include 'base/partials/info_search.html' %}
                                    <div class="input-group-append">
                                        <button type="button" id="busqueda" class="btn btn-lg btn-default">
                                            <i class="fa fa-search"></i>
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                        {% if perms.productos.add_tipoproducto %}
                        <div class="float-right">
                            <button type="button" class="btn btn-block btn-primary"
                                onclick="abrir_modal_creacion('/producto/tipoProducto/add/')">Agregar nuevo registro</button>
                        </div>
                        {% endif %}
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="list_tipo" class="table table-bordered table-hover"
                            style="margin: auto;">
                            <thead>
                                <tr>
                                    <th>Nombre tipo</th>
                                    <th>Fecha alta</th>
                                    <th>Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</section>

<div class="modal fade" id="creacion" role="dialog">

</div>

<div class="modal fade" id="edicion" role="dialog">

</div>

<div class="modal fade" id="eliminacion" role="dialog">

</div>

{% endblock content %}

{% block js_page %}
{{ block.super }}
<!-- Datatables -->
<script>
    $(function () {
        $('input').on("cut copy paste", function (e) {
            e.preventDefault();
        });

        var get_list = function (busqueda) {
            $("#list_tipo").DataTable({
                destroy: true,
                //dom: 'Bfrtip',
                // buttons: [                
                //     {
                //         extend: 'pdfHtml5',
                //         text: 'Exportar PDF',
                //         exportOptions: {
                //             columns: [0,1]
                //         }
                //     },
                // ],
                searching: false,
                pageLength: 10,
                ajax: {
                    url: "/producto/tipoProducto/get_list_tipo_producto/",
                    type: 'GET',
                    datatype: 'json',
                    data: { 'busqueda': busqueda },
                    error: function (data) {
                        $.fn.DataTable.ext.errorMode = 'none'
                    }
                },
                columns: [
                    {
                        name: 'Nombre tipo',
                        data: 'nombre_tipo',
                    },
                    {
                        name: 'Fecha alta',
                        data: 'fecha_alta',
                    },
                    {
                        name: 'Acciones',
                        data: 'id',
                        render: function (data) {
                            var buttons = ""
                            {% if perms.productos.change_tipoproducto %}
                                buttons += '<button class="btn btn-warning" onclick="abrir_modal_edicion(\'/producto/tipoProducto/edit/' + data + '/\');">\
                                                        Editar\
                                                    </button>';
                            {% endif %}

                            {% if perms.productos.change_tipoproducto %}
                            buttons += '<button class="btn btn-danger ml-2" onclick="eliminar_registro(\'/producto/tipoProducto/baja/' + data + '/\', \'/producto/tipoProducto/list/\');">\
                                                    Baja\
                                                    </button>';
                            {% endif %}

                            return buttons;

                        }
                    }
                ],
                columnDefs: [{
                    targets: [2], // column index (start from 0)
                    orderable: false, // set orderable false for selected columns
                }],
                serverSide: false,
                language: {
                    decimal: "",
                    emptyTable: "Sin resultados encontrados",
                    info: "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
                    infoEmpty: "Mostrando 0 de 0 Entradas",
                    infoFiltered: "(Filtrado de _MAX_ total entradas)",
                    infoPostFix: "",
                    thousands: ",",
                    lengthMenu: "Mostrar _MENU_ Entradas",
                    loadingRecords: "Cargando...",
                    processing: "Procesando...",
                    search: "Buscar:",
                    zeroRecords: "Sin resultados encontrados",
                    paginate: {
                        first: "Primero",
                        last: "Ultimo",
                        next: "Siguiente",
                        previous: "Anterior",
                    },
                },

            })
        }

        var query = ""

        get_list(query);

        $("#searchTerm").change(function () {
            var busqueda = $("#searchTerm").val()
            sessionStorage.setItem("busqueda", busqueda)
        })

        $("#busqueda").click(function () {
            var busqueda = sessionStorage.getItem("busqueda")
            if (busqueda == "" || busqueda == undefined || busqueda == null) {
                busqueda = "";
                get_list(busqueda)
            }
            else {
                get_list(busqueda)
            }
        })

        {% if messages %}
            {% for message in messages %}
                var text = "{{ message }}";
                add_edit_registro(text);
            {% endfor %}
        {% endif %}
    })
</script>


{% endblock js_page %}